cluster_name: production-web-forx

tags:
  owner: "Webforx Technology"
  team: "Webforx Team"
  environment: "production"
  project: "webforx"
  create_by: "Terraform"
  cloud_provider: "aws"

s3_backend:
  aws_region_main: "us-east-1"
  aws_region_backup: "us-east-2"
  force_destroy: true

vpc:
  cidr_block: 172.16.0.0/16
  availability_zones: [
    "us-east-1a", 
    "us-east-1b", 
    "us-east-1c"
  ]